service: kijani-receipt-chain

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  generateReceipt:
    handler: kk-receipts/handler.generateReceipt
    events:
      - httpApi:
          path: /receipts
          method: post

  processReceipt:
    handler: kk-processor/handler.processReceipt
    events:
      - httpApi:
          path: /internal/process-receipt
          method: post
